apiVersion: v1
kind: Secret
metadata:
  name: ${KUBE_NAMESPACE}-secrets
  namespace: ${KUBE_NAMESPACE}
type: Opaque
stringData:
  SESSION_SECRET: '${SESSION_SECRET}'
  BETA_ACCESS_PASSWORDS: '${BETA_ACCESS_PASSWORDS}'
  HASH_SECRET: '${HASH_SECRET}'
