apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: care-arrangement-plan-staging-redirect
  namespace: care-arrangement-plan-staging
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: care-arrangement-plan-staging-redirect-care-arrangement-plan-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: '100'
    nginx.ingress.kubernetes.io/permanent-redirect: "https://staging.child-arrangements-plan.service.justice.gov.uk"
spec:
  ingressClassName: modsec
  tls:
    - hosts:
        - care-arrangement-plan-staging.apps.live.cloud-platform.service.justice.gov.uk
  rules:
    - host: care-arrangement-plan-staging.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: care-arrangement-plan-staging-node-service
                port:
                  number: 8080
