apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: connecting-services-staging-ingress
  namespace: connecting-services-staging
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: connecting-services-staging-ingress-connecting-services-staging-green
    external-dns.alpha.kubernetes.io/aws-weight: '100'
    nginx.ingress.kubernetes.io/enable-modsecurity: 'true'
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecAuditEngine On
      SecRuleEngine DetectionOnly
      SecDefaultAction "phase:2,pass,log,tag:github_team=central-digital-product-team,tag:namespace=connecting-services-staging"
    nginx.ingress.kubernetes.io/server-snippet: |
      location = /health {
        auth_basic off;
        access_log off;
        default_type text/plain;
        add_header Content-Type text/plain;
        return 200 "OK";
      }

      location = /.well-known/security.txt {
        auth_basic off;
        return 301 https://raw.githubusercontent.com/ministryofjustice/security-guidance/main/contact/vulnerability-disclosure-security.txt;
      }
spec:
  ingressClassName: modsec
  tls:
    - hosts:
        - connecting-services-staging.apps.live.cloud-platform.service.justice.gov.uk
      secretName: pfl-connecting-services-cert-secret
  rules:
    - host: connecting-services-staging.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: connecting-services-staging-node-service
                port:
                  number: 8080
