name: 'Build & Push Image'

on:
  workflow_call:
    outputs:
      registry:
        description: 'AWS registry where the ECR is located'
        value: ${{ jobs.image_build.outputs.registry }}

jobs:
  image_build:
    name: 'Build'
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.ecr-login.outputs.registry }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.ECR_REGION }}

      - name: 'Log into ECR'
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076
        id: ecr-login

      - name: 'Build & Push to ECR'
        run: |

          # ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░

          docker image build -t $REGISTRY/$REPOSITORY:node-$IMAGE_TAG .
          docker image push $REGISTRY/$REPOSITORY:node-$IMAGE_TAG

          # ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░  ░░

        env:
          REGISTRY: ${{ steps.ecr-login.outputs.registry }}
          REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
