name: Deploy release directly to Cloud Platform

on:
  # On https://github.com/ministryofjustice/care-arrangement-plan/actions/workflows/release-trigger.yml
  # use the 'Run workflow' button to trigger this workflow.
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Target environment
        options:
        - development
        - staging
        - production

jobs:
  validate:
    name: 'Validate'
    uses: ./.github/workflows/validation.yml
    secrets: inherit

  image:
    name: 'Build & Push Image'
    uses: ./.github/workflows/build-push-image.yml
    needs: [validate]
    secrets: inherit

  deploy_development:
    name: 'Deploy to Development'
    if: github.event.inputs.environment == 'development'
    uses: ./.github/workflows/deploy.yml
    needs: [image, validate]
    with:
      environment: development
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  deploy_staging:
    name: 'Deploy to Staging'
    if: github.event.inputs.environment == 'staging'
    uses: ./.github/workflows/deploy.yml
    needs: [image, validate]
    with:
      environment: staging
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit

  deploy_production:
    name: 'Deploy to Production'
    if: github.event.inputs.environment == 'production'
    needs: [image, validate]
    uses: ./.github/workflows/deploy.yml
    with:
      environment: production
      registry: ${{ needs.image.outputs.registry }}
    secrets: inherit
