name: Validation

on:
  workflow_call:
  pull_request:
  schedule:
    - cron: '0 8 * * 2'

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: 'Setup Node.js'
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
        with:
          node-version-file: '.nvmrc'

      - name: 'Install Dependencies'
        run: npm ci --no-audit

      - name: 'Run Linter'
        run: npm run lint

      - name: 'Run Typecheck'
        run: npm run typecheck

      - name: 'Run Unit Tests'
        run: npm run test:ci

      - name: 'Install Playwright Browsers'
        run: npx playwright install --with-deps chromium

      - name: 'Run Playwright E2E Tests'
        run: npm run e2e

      - name: 'Upload Playwright Report'
        if: always()
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
